version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: mongo:latest

  catalog.api:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: MicroServies/Catalog/Catalog.API/Dockerfile

  ekartweb:
    image: ${DOCKER_REGISTRY-}ekartweb
    build:
      context: .
      dockerfile: WebApps/EKartWeb/Dockerfile

volumes:
  mongo_data:
